### ISSUE TITLE
Misskeyのチャット機能削除に対応する

### ISSUE THREAD

**Issue by na2na-p** [syuilo/ai#101]
# やること

- 既存のチャット機能使っている箇所をDMに置換する？

# Why

see: https://github.com/misskey-dev/misskey/blob/develop/CHANGELOG.md
まだ全体像把握して無いですが、いくつかの機能が壊れる気がします。

**Comment by na2na-p** [comment]
@syuilo 
チャットの存在しているバージョンのMisskeyとの互換性ってどうする予定、とかありますか？

**Comment by syuilo** [comment]
DMを使うようにすれば後方互換性は保たれるから良いと思う

**Comment by na2na-p** [comment]
たしかに

**Comment by na2na-p** [comment]
@syuilo 

相談その1
https://github.com/syuilo/ai/blob/ecb983089cb1366cffe62afa633d0d2273ac6671/src/ai.ts#L386-L390

上記実装について、
- 削除して利用側には`ai.post()`を使わせる
- `ai.sendMessage()`は`ai.post()`のラップとして簡単に呼び出せるように、かつ利用側での使い方は今と変わらないようにする

のどっちがいいですか？

相談その2

https://github.com/syuilo/ai/blob/master/src/message.ts

上記実装からメッセージ(チャット)要素を消し去るだけに留めて破壊的変更はしない、でいいですか？

**Comment by syuilo** [comment]
> 相談その1

(無いとは思うけど)今後チャットが復活する可能性も0ではないしラップで良いんじゃないかしら

> 相談その2

良さそう

**Comment by syuilo** [comment]
しゅいろさんがやってみるからなずな待って

**Comment by syuilo** [comment]
@na2na-p めんどくさいからごっそり消した
https://github.com/syuilo/ai/pull/102

**Comment by syuilo** [comment]
チャット復活した
