### ISSUE TITLE
ん... うたた寝しちゃってました

### ISSUE THREAD

**Issue by DA-TENSHI** [syuilo/ai#119]
![image](https://github.com/syuilo/ai/assets/107112367/0939c783-73bb-43e3-84c2-9b703781335f)
写真のように藍ちゃんが「ん... うたた寝しちゃってました」と多重投稿します。
環境はWSL2でUbuntu22.04 LTSです。
相手側クライアントは12.119.2-taiyme-v1.2.0(submarin.online)
ノーマル藍ちゃんを動かしてます。
再起動したら治りました。
Issueはあったのですが、回答がよくわからんかったので、再度issueを開きました。

**Comment by massongit** [comment]
以下を確認してみてはいかがでしょうか？

* `config.json` の `keywordEnabled` が `true` の場合、MeCabと `mecab-ipadic-neologd` がインストールいるか確認する (もしくは  `config.json` の `keywordEnabled` を `false` にする)
* `config.json` の `chartEnabled` が `true` の場合、 `font.ttf` を配置しているか確認する (もしくは  `config.json` の `chartEnabled` を `false` にする)

**Comment by DA-TENSHI** [comment]
ありがとうございます。一度確認してみます。

**Comment by DA-TENSHI** [comment]
確認し、font.ttfが見つからなかったので追加した結果、暴走が収まりました。
ありがとうございました!
