### ISSUE TITLE
Misskey v13.14.2にてお誕生日を祝おうとして落ちる

### ISSUE THREAD

**Issue by tai-cha** [syuilo/ai#120]
チャットに送ろうとするがチャットがないため？

`ai.sendMessage`が残っているからこれを叩こうとして落ちるっぽいですね
チョコ配りも残ってそう

**Comment by taichanNE30** [comment]
エラーハンドリングがないので設定を間違えないことが重要（自分が設定ミスってました）

**Comment by taichanNE30** [comment]
と思ったけどエラーハンドリングがなくて際限なくうたた寝してしまうので一応Openのままに

**Comment by taichanNE30** [comment]
#101 #102 で削除対応したっぽいけど残ってるやつだ

**Comment by taichanNE30** [comment]
めんどくさくて消した経緯とかがありそうなのでどう対応していいのか難しいですね
できれば（忙しそうなのでご迷惑おかけしたくないですが）@syuilo さんの意見も聞きたい

**Comment by syuilo** [comment]
DMで送るようにしても良いかも

**Comment by taichanNE30** [comment]
じゃあ #101 で言われてたようなラップする方式がいいですかね…！
#102 を見る限り一旦omitするので問題なさそうなのでsendMessageの中を書き換える感じで書いてみます～

**Comment by tai-cha** [comment]
おそらく #121 で対応済み
