### ISSUE TITLE
現在時刻に元ずいた挨拶をする

### ISSUE THREAD

**Issue by u1-liquid** [syuilo/ai#36]
今の藍ちゃんは優しすぎて深夜におはようとか真昼におやすみしても丁寧に返事してくれますが、
流石に体に悪そうな言動なので心配してくれるとか（親愛度高い時）だめだめな奴だと責めてくれると（親愛度低い時？）国民の健康に貢献できそう

**Comment by syuilo** [comment]
これかしら
https://github.com/syuilo/ai/issues/4

**Comment by u1-liquid** [comment]
やっぱもう在ったかー
