### ISSUE TITLE
keywordモジュールを有効にしていると、Windows環境で任意のコマンドが実行できる

### ISSUE THREAD

**Issue by CookieRamen** [syuilo/ai#63]
https://misskey.io/notes/8caaygpzgv

https://misskey.io/notes/8cab88yqoc

![image](https://user-images.githubusercontent.com/37681609/93466213-dbcdea00-f926-11ea-9096-3b74e722ec15.png)

**Comment by syuilo** [comment]
再現手順ってありますか？👀

**Comment by CookieRamen** [comment]
学習実行タイミングを1分間隔ぐらいにして、`a | calc b`を拾わせる

**Comment by syuilo** [comment]
なるほど。keywordモジュールが有効になっている必要があると
https://github.com/hecomi/node-mecab-async
に脆弱性ありそう

**Comment by syuilo** [comment]
2017年が最後のコミットになってるからメンテされてない可能性ありそう
