### ISSUE TITLE
mecab-asyncをpackage.jsonに追記していない

### ISSUE THREAD

**Issue by YuzuRyo61** [syuilo/ai#66]
package.jsonに`mecab-async`を入れ忘れています。

![image](https://user-images.githubusercontent.com/18282413/96358248-0be3f500-1140-11eb-80bf-bb88e903bd09.png)

**Comment by syuilo** [comment]
mecab-asyncは使っていないので古いファイルが残っているのかも
built 消してリビルドすると直るかも
